version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
    labels:
      - "part:tooling"
      - "type:tech-debt"
    reviewers:
      - "frequenz-floss/python-sdk-team"
    # Default versioning-strategy. For other versioning-strategy see:
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy
    versioning-strategy: auto
    # Allow up to 10 open pull requests for updates to dependency versions
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
    labels:
      - "part:tooling"
      - "type:tech-debt"
    reviewers:
      - "frequenz-floss/python-sdk-team"

  # Security updates for supported branches

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "part:tooling"
      - "type:tech-debt"
      - "priority:URGENT"
    reviewers:
      - "frequenz-floss/python-sdk-team"
    open-pull-requests-limit: 0 # Disable version updates
    target-branch: "v0.16.x"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "part:tooling"
      - "type:tech-debt"
      - "priority:URGENT"
    reviewers:
      - "frequenz-floss/python-sdk-team"
    open-pull-requests-limit: 0 # Disable version updates
    target-branch: "v0.16.x"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "part:tooling"
      - "type:tech-debt"
      - "priority:URGENT"
    reviewers:
      - "frequenz-floss/python-sdk-team"
    open-pull-requests-limit: 0 # Disable version updates
    target-branch: "v0.17.x"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "part:tooling"
      - "type:tech-debt"
      - "priority:URGENT"
    reviewers:
      - "frequenz-floss/python-sdk-team"
    open-pull-requests-limit: 0 # Disable version updates
    target-branch: "v0.17.x"
