version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
    labels:
      - "part:tooling"
    reviewers:
      - daniel-zullo-frequenz
      # - "frequenz-floss/python-sdk-team"
